---
#
# Ansible managed
#
repository:
  description: Install and configure automatic package updates on your system.
  homepage: https://robertdebock.nl/
  topics: autoupdate, security, system, ansible, molecule, tox, playbook
