---
# tasks file for auto_update
- name: include assert.yml
  include_tasks: assert.yml

- name: install packages
  package:
    name: "{{ auto_update_packages }}"
    state: present

- name: configure auto_update
  template:
    src: "{{ auto_update_config_file }}.j2"
    dest: "{{ auto_update_config_directory }}/{{ auto_update_config_file }}"
    mode: "0644"

- name: start and enable auto_update
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop: "{{ auto_update_services }}"
